### PR TITLE
Upgrade Python version from 3.7 to 3.8

### PR DESCRIPTION
**Pull request by mabunday**
*Issue #, if available:*

AWSALGO-5729

*Description of changes:*

Upgrade Python version from 3.7 to 3.8

*Testing:*

* Beta integration tests
* Gamma integration tests

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Related issue: #117. 
I am also hoping for a Python upgrade. However, are you using the lastest default branch? I see there were some changes merged into it recently that seemed to bump the Python version: https://github.com/aws/sagemaker-scikit-learn-container/commit/e506d34c9834276d8409e317131e5d782b4a39f8

**Comment by lorenzwalthert** [comment]
@mabunday Python 3.9 is in master already I think.

**Comment by mabunday** [comment]
Its in master but not everything was configured correctly and the changes weren't deployed to public ECRs due to some failing checks. We do plan on upgrading to the latest versions of Python, but we're taking an incremental approach right now to minimize the number of changes needed.

**Review by secastillo — APPROVED** [review]

**Comment by mabunday** [comment]
I'm going to merge these changes but noting that since we had to downgrade pyarrow here for mlio compatibility, to just keep this issue in mind: https://github.com/aws/sagemaker-scikit-learn-container/issues/106

A fast-follow PR should see if we can bump pyarrow back to 3.0 while still passing integration tests.

**Pull request merged**
